// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: proto/partner/partner.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartnerService_GetDeviceSnapshot_FullMethodName = "/partner.PartnerService/GetDeviceSnapshot"
	PartnerService_ListDevicesByWard_FullMethodName = "/partner.PartnerService/ListDevicesByWard"
)

// PartnerServiceClient is the client API for PartnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Third-party facing gRPC surface — see docs/partner-api-guide.md for the full integration
// guide and docs/adr/0012-partner-api-grpc-transport.md for why this is gRPC (not REST) and
// docs/adr/0011-partner-device-no-persist-proxy.md for why access is scoped by ward (not
// per-serial) and readings are proxied, not persisted. Admin key issuance stays REST
// (/admin/partner-keys) on SMtrack's side, unrelated to this contract.
type PartnerServiceClient interface {
	// Device metadata + trailing 1 hour of telemetry, always — no arbitrary date range.
	GetDeviceSnapshot(ctx context.Context, in *GetDeviceSnapshotRequest, opts ...grpc.CallOption) (*GetDeviceSnapshotResponse, error)
	// Every device in `ward` (that the caller's key is scoped to) plus each device's single
	// latest telemetry reading — not the full history.
	ListDevicesByWard(ctx context.Context, in *ListDevicesByWardRequest, opts ...grpc.CallOption) (*ListDevicesByWardResponse, error)
}

type partnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnerServiceClient(cc grpc.ClientConnInterface) PartnerServiceClient {
	return &partnerServiceClient{cc}
}

func (c *partnerServiceClient) GetDeviceSnapshot(ctx context.Context, in *GetDeviceSnapshotRequest, opts ...grpc.CallOption) (*GetDeviceSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceSnapshotResponse)
	err := c.cc.Invoke(ctx, PartnerService_GetDeviceSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) ListDevicesByWard(ctx context.Context, in *ListDevicesByWardRequest, opts ...grpc.CallOption) (*ListDevicesByWardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesByWardResponse)
	err := c.cc.Invoke(ctx, PartnerService_ListDevicesByWard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerServiceServer is the server API for PartnerService service.
// All implementations must embed UnimplementedPartnerServiceServer
// for forward compatibility.
//
// Third-party facing gRPC surface — see docs/partner-api-guide.md for the full integration
// guide and docs/adr/0012-partner-api-grpc-transport.md for why this is gRPC (not REST) and
// docs/adr/0011-partner-device-no-persist-proxy.md for why access is scoped by ward (not
// per-serial) and readings are proxied, not persisted. Admin key issuance stays REST
// (/admin/partner-keys) on SMtrack's side, unrelated to this contract.
type PartnerServiceServer interface {
	// Device metadata + trailing 1 hour of telemetry, always — no arbitrary date range.
	GetDeviceSnapshot(context.Context, *GetDeviceSnapshotRequest) (*GetDeviceSnapshotResponse, error)
	// Every device in `ward` (that the caller's key is scoped to) plus each device's single
	// latest telemetry reading — not the full history.
	ListDevicesByWard(context.Context, *ListDevicesByWardRequest) (*ListDevicesByWardResponse, error)
	mustEmbedUnimplementedPartnerServiceServer()
}

// UnimplementedPartnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartnerServiceServer struct{}

func (UnimplementedPartnerServiceServer) GetDeviceSnapshot(context.Context, *GetDeviceSnapshotRequest) (*GetDeviceSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceSnapshot not implemented")
}
func (UnimplementedPartnerServiceServer) ListDevicesByWard(context.Context, *ListDevicesByWardRequest) (*ListDevicesByWardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevicesByWard not implemented")
}
func (UnimplementedPartnerServiceServer) mustEmbedUnimplementedPartnerServiceServer() {}
func (UnimplementedPartnerServiceServer) testEmbeddedByValue()                        {}

// UnsafePartnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartnerServiceServer will
// result in compilation errors.
type UnsafePartnerServiceServer interface {
	mustEmbedUnimplementedPartnerServiceServer()
}

func RegisterPartnerServiceServer(s grpc.ServiceRegistrar, srv PartnerServiceServer) {
	// If the following call panics, it indicates UnimplementedPartnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartnerService_ServiceDesc, srv)
}

func _PartnerService_GetDeviceSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetDeviceSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_GetDeviceSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetDeviceSnapshot(ctx, req.(*GetDeviceSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_ListDevicesByWard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesByWardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).ListDevicesByWard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_ListDevicesByWard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).ListDevicesByWard(ctx, req.(*ListDevicesByWardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartnerService_ServiceDesc is the grpc.ServiceDesc for PartnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "partner.PartnerService",
	HandlerType: (*PartnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceSnapshot",
			Handler:    _PartnerService_GetDeviceSnapshot_Handler,
		},
		{
			MethodName: "ListDevicesByWard",
			Handler:    _PartnerService_ListDevicesByWard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/partner/partner.proto",
}
