// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: proto/partner/partner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeviceSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceSnapshotRequest) Reset() {
	*x = GetDeviceSnapshotRequest{}
	mi := &file_proto_partner_partner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceSnapshotRequest) ProtoMessage() {}

func (x *GetDeviceSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partner_partner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_partner_partner_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceSnapshotRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type DeviceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serial        string                 `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Firmware      string                 `protobuf:"bytes,4,opt,name=firmware,proto3" json:"firmware,omitempty"`
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMetadata) Reset() {
	*x = DeviceMetadata{}
	mi := &file_proto_partner_partner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMetadata) ProtoMessage() {}

func (x *DeviceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partner_partner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMetadata.ProtoReflect.Descriptor instead.
func (*DeviceMetadata) Descriptor() ([]byte, []int) {
	return file_proto_partner_partner_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceMetadata) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceMetadata) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeviceMetadata) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *DeviceMetadata) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type TelemetryPoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SendTime        string                 `protobuf:"bytes,1,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"` // ISO 8601 UTC
	Temp            float64                `protobuf:"fixed64,2,opt,name=temp,proto3" json:"temp,omitempty"`
	TempDisplay     float64                `protobuf:"fixed64,3,opt,name=temp_display,json=tempDisplay,proto3" json:"temp_display,omitempty"`
	Humidity        float64                `protobuf:"fixed64,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	HumidityDisplay float64                `protobuf:"fixed64,5,opt,name=humidity_display,json=humidityDisplay,proto3" json:"humidity_display,omitempty"`
	TempInternal    float64                `protobuf:"fixed64,6,opt,name=temp_internal,json=tempInternal,proto3" json:"temp_internal,omitempty"`
	Battery         int32                  `protobuf:"varint,7,opt,name=battery,proto3" json:"battery,omitempty"`
	Plug            bool                   `protobuf:"varint,8,opt,name=plug,proto3" json:"plug,omitempty"`
	Door1           bool                   `protobuf:"varint,9,opt,name=door1,proto3" json:"door1,omitempty"`
	Door2           bool                   `protobuf:"varint,10,opt,name=door2,proto3" json:"door2,omitempty"`
	Door3           bool                   `protobuf:"varint,11,opt,name=door3,proto3" json:"door3,omitempty"`
	Internet        bool                   `protobuf:"varint,12,opt,name=internet,proto3" json:"internet,omitempty"`
	ExtMemory       bool                   `protobuf:"varint,13,opt,name=ext_memory,json=extMemory,proto3" json:"ext_memory,omitempty"`
	Probe           string                 `protobuf:"bytes,14,opt,name=probe,proto3" json:"probe,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryPoint) Reset() {
	*x = TelemetryPoint{}
	mi := &file_proto_partner_partner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPoint) ProtoMessage() {}

func (x *TelemetryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partner_partner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPoint.ProtoReflect.Descriptor instead.
func (*TelemetryPoint) Descriptor() ([]byte, []int) {
	return file_proto_partner_partner_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryPoint) GetSendTime() string {
	if x != nil {
		return x.SendTime
	}
	return ""
}

func (x *TelemetryPoint) GetTemp() float64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *TelemetryPoint) GetTempDisplay() float64 {
	if x != nil {
		return x.TempDisplay
	}
	return 0
}

func (x *TelemetryPoint) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *TelemetryPoint) GetHumidityDisplay() float64 {
	if x != nil {
		return x.HumidityDisplay
	}
	return 0
}

func (x *TelemetryPoint) GetTempInternal() float64 {
	if x != nil {
		return x.TempInternal
	}
	return 0
}

func (x *TelemetryPoint) GetBattery() int32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *TelemetryPoint) GetPlug() bool {
	if x != nil {
		return x.Plug
	}
	return false
}

func (x *TelemetryPoint) GetDoor1() bool {
	if x != nil {
		return x.Door1
	}
	return false
}

func (x *TelemetryPoint) GetDoor2() bool {
	if x != nil {
		return x.Door2
	}
	return false
}

func (x *TelemetryPoint) GetDoor3() bool {
	if x != nil {
		return x.Door3
	}
	return false
}

func (x *TelemetryPoint) GetInternet() bool {
	if x != nil {
		return x.Internet
	}
	return false
}

func (x *TelemetryPoint) GetExtMemory() bool {
	if x != nil {
		return x.ExtMemory
	}
	return false
}

func (x *TelemetryPoint) GetProbe() string {
	if x != nil {
		return x.Probe
	}
	return ""
}

type GetDeviceSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceMetadata        `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Timeseries    []*TelemetryPoint      `protobuf:"bytes,2,rep,name=timeseries,proto3" json:"timeseries,omitempty"` // last 1h, newest first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceSnapshotResponse) Reset() {
	*x = GetDeviceSnapshotResponse{}
	mi := &file_proto_partner_partner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceSnapshotResponse) ProtoMessage() {}

func (x *GetDeviceSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partner_partner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_partner_partner_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceSnapshotResponse) GetDevice() *DeviceMetadata {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *GetDeviceSnapshotResponse) GetTimeseries() []*TelemetryPoint {
	if x != nil {
		return x.Timeseries
	}
	return nil
}

type ListDevicesByWardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ward          string                 `protobuf:"bytes,1,opt,name=ward,proto3" json:"ward,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`   // optional, default 1
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // optional, default 20, max 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesByWardRequest) Reset() {
	*x = ListDevicesByWardRequest{}
	mi := &file_proto_partner_partner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesByWardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesByWardRequest) ProtoMessage() {}

func (x *ListDevicesByWardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partner_partner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesByWardRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesByWardRequest) Descriptor() ([]byte, []int) {
	return file_proto_partner_partner_proto_rawDescGZIP(), []int{4}
}

func (x *ListDevicesByWardRequest) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

func (x *ListDevicesByWardRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDevicesByWardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DeviceWithLatestReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceMetadata        `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Latest        *TelemetryPoint        `protobuf:"bytes,2,opt,name=latest,proto3,oneof" json:"latest,omitempty"` // unset if the device has no telemetry yet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceWithLatestReading) Reset() {
	*x = DeviceWithLatestReading{}
	mi := &file_proto_partner_partner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceWithLatestReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceWithLatestReading) ProtoMessage() {}

func (x *DeviceWithLatestReading) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partner_partner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceWithLatestReading.ProtoReflect.Descriptor instead.
func (*DeviceWithLatestReading) Descriptor() ([]byte, []int) {
	return file_proto_partner_partner_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceWithLatestReading) GetDevice() *DeviceMetadata {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *DeviceWithLatestReading) GetLatest() *TelemetryPoint {
	if x != nil {
		return x.Latest
	}
	return nil
}

type ListDevicesByWardResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Devices       []*DeviceWithLatestReading `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	Total         int32                      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                      `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                      `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesByWardResponse) Reset() {
	*x = ListDevicesByWardResponse{}
	mi := &file_proto_partner_partner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesByWardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesByWardResponse) ProtoMessage() {}

func (x *ListDevicesByWardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partner_partner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesByWardResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesByWardResponse) Descriptor() ([]byte, []int) {
	return file_proto_partner_partner_proto_rawDescGZIP(), []int{6}
}

func (x *ListDevicesByWardResponse) GetDevices() []*DeviceWithLatestReading {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ListDevicesByWardResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDevicesByWardResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDevicesByWardResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_partner_partner_proto protoreflect.FileDescriptor

const file_proto_partner_partner_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/partner/partner.proto\x12\apartner\"2\n" +
	"\x18GetDeviceSnapshotRequest\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\"\x88\x01\n" +
	"\x0eDeviceMetadata\x12\x16\n" +
	"\x06serial\x18\x01 \x01(\tR\x06serial\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\x12\x1a\n" +
	"\bfirmware\x18\x04 \x01(\tR\bfirmware\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\"\x91\x03\n" +
	"\x0eTelemetryPoint\x12\x1b\n" +
	"\tsend_time\x18\x01 \x01(\tR\bsendTime\x12\x12\n" +
	"\x04temp\x18\x02 \x01(\x01R\x04temp\x12!\n" +
	"\ftemp_display\x18\x03 \x01(\x01R\vtempDisplay\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\x01R\bhumidity\x12)\n" +
	"\x10humidity_display\x18\x05 \x01(\x01R\x0fhumidityDisplay\x12#\n" +
	"\rtemp_internal\x18\x06 \x01(\x01R\ftempInternal\x12\x18\n" +
	"\abattery\x18\a \x01(\x05R\abattery\x12\x12\n" +
	"\x04plug\x18\b \x01(\bR\x04plug\x12\x14\n" +
	"\x05door1\x18\t \x01(\bR\x05door1\x12\x14\n" +
	"\x05door2\x18\n" +
	" \x01(\bR\x05door2\x12\x14\n" +
	"\x05door3\x18\v \x01(\bR\x05door3\x12\x1a\n" +
	"\binternet\x18\f \x01(\bR\binternet\x12\x1d\n" +
	"\n" +
	"ext_memory\x18\r \x01(\bR\textMemory\x12\x14\n" +
	"\x05probe\x18\x0e \x01(\tR\x05probe\"\x85\x01\n" +
	"\x19GetDeviceSnapshotResponse\x12/\n" +
	"\x06device\x18\x01 \x01(\v2\x17.partner.DeviceMetadataR\x06device\x127\n" +
	"\n" +
	"timeseries\x18\x02 \x03(\v2\x17.partner.TelemetryPointR\n" +
	"timeseries\"X\n" +
	"\x18ListDevicesByWardRequest\x12\x12\n" +
	"\x04ward\x18\x01 \x01(\tR\x04ward\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8b\x01\n" +
	"\x17DeviceWithLatestReading\x12/\n" +
	"\x06device\x18\x01 \x01(\v2\x17.partner.DeviceMetadataR\x06device\x124\n" +
	"\x06latest\x18\x02 \x01(\v2\x17.partner.TelemetryPointH\x00R\x06latest\x88\x01\x01B\t\n" +
	"\a_latest\"\x97\x01\n" +
	"\x19ListDevicesByWardResponse\x12:\n" +
	"\adevices\x18\x01 \x03(\v2 .partner.DeviceWithLatestReadingR\adevices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit2\xc8\x01\n" +
	"\x0ePartnerService\x12Z\n" +
	"\x11GetDeviceSnapshot\x12!.partner.GetDeviceSnapshotRequest\x1a\".partner.GetDeviceSnapshotResponse\x12Z\n" +
	"\x11ListDevicesByWard\x12!.partner.ListDevicesByWardRequest\x1a\".partner.ListDevicesByWardResponseBLZJgithub.com/efangly/thanes-lims-backend/internal/adapters/partnergrpc/pb;pbb\x06proto3"

var (
	file_proto_partner_partner_proto_rawDescOnce sync.Once
	file_proto_partner_partner_proto_rawDescData []byte
)

func file_proto_partner_partner_proto_rawDescGZIP() []byte {
	file_proto_partner_partner_proto_rawDescOnce.Do(func() {
		file_proto_partner_partner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_partner_partner_proto_rawDesc), len(file_proto_partner_partner_proto_rawDesc)))
	})
	return file_proto_partner_partner_proto_rawDescData
}

var file_proto_partner_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_partner_partner_proto_goTypes = []any{
	(*GetDeviceSnapshotRequest)(nil),  // 0: partner.GetDeviceSnapshotRequest
	(*DeviceMetadata)(nil),            // 1: partner.DeviceMetadata
	(*TelemetryPoint)(nil),            // 2: partner.TelemetryPoint
	(*GetDeviceSnapshotResponse)(nil), // 3: partner.GetDeviceSnapshotResponse
	(*ListDevicesByWardRequest)(nil),  // 4: partner.ListDevicesByWardRequest
	(*DeviceWithLatestReading)(nil),   // 5: partner.DeviceWithLatestReading
	(*ListDevicesByWardResponse)(nil), // 6: partner.ListDevicesByWardResponse
}
var file_proto_partner_partner_proto_depIdxs = []int32{
	1, // 0: partner.GetDeviceSnapshotResponse.device:type_name -> partner.DeviceMetadata
	2, // 1: partner.GetDeviceSnapshotResponse.timeseries:type_name -> partner.TelemetryPoint
	1, // 2: partner.DeviceWithLatestReading.device:type_name -> partner.DeviceMetadata
	2, // 3: partner.DeviceWithLatestReading.latest:type_name -> partner.TelemetryPoint
	5, // 4: partner.ListDevicesByWardResponse.devices:type_name -> partner.DeviceWithLatestReading
	0, // 5: partner.PartnerService.GetDeviceSnapshot:input_type -> partner.GetDeviceSnapshotRequest
	4, // 6: partner.PartnerService.ListDevicesByWard:input_type -> partner.ListDevicesByWardRequest
	3, // 7: partner.PartnerService.GetDeviceSnapshot:output_type -> partner.GetDeviceSnapshotResponse
	6, // 8: partner.PartnerService.ListDevicesByWard:output_type -> partner.ListDevicesByWardResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_partner_partner_proto_init() }
func file_proto_partner_partner_proto_init() {
	if File_proto_partner_partner_proto != nil {
		return
	}
	file_proto_partner_partner_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_partner_partner_proto_rawDesc), len(file_proto_partner_partner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_partner_partner_proto_goTypes,
		DependencyIndexes: file_proto_partner_partner_proto_depIdxs,
		MessageInfos:      file_proto_partner_partner_proto_msgTypes,
	}.Build()
	File_proto_partner_partner_proto = out.File
	file_proto_partner_partner_proto_goTypes = nil
	file_proto_partner_partner_proto_depIdxs = nil
}
